[programs.devnet]
myepicproject = "4HcMYQPwtUrcd1R1qEkNnvSw2xQhmYrRfRMrr3uqa1BU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/santiagosarabia/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
